[Solved #105] Race end controllers
the-ai-team/razor pull request #108
Opened 2023-10-23 15:03 UTC by supunTE

2023-11-01 18:00 UTC, dalanad requested changes

2023-11-01 18:00 UTC, dalanad commented on apps/client/src/pages/race/Race.page.tsx
> +  const raceTimeEndHandler = (): void => {
`raceEndHandler`

2023-11-01 18:00 UTC, dalanad commented on libs/models/src/lib/sockets/protocols.ts
> +  // ForceEnd = 'FORCE_END',
Why is this ?

2023-12-05 04:50 UTC, supunTE commented on libs/models/src/lib/sockets/protocols.ts
> +  // ForceEnd = 'FORCE_END',
This was initially intended to be a separate protocol. However, I later discovered we could handle this event within sendLeaderboard. I kept the protocol until the implementation of sendLeaderboard was completed. It has now been removed in the latest PRs.
ab2b857b81490c2cee3f0476ca2cd3beae5cc2aa

2023-12-05 04:51 UTC, supunTE commented on apps/client/src/pages/race/Race.page.tsx
> +  const raceTimeEndHandler = (): void => {
renamed in #114 5feab21e8a824365acd9e9de9cfe2cd16090c19e

2023-12-12 11:40 UTC, dalanad approved these changes

2024-03-18 10:03 UTC, merged