[Fix #33] Complete requested changes
the-ai-team/razor pull request #52
Opened 2023-02-09 06:38 UTC by supunTE

- Initialize default values when props are destrucring.
- Add docs for component props

2023-02-22 04:21 UTC, dalanad requested changes

2023-02-22 04:21 UTC, dalanad commented on apps/client/src/components/molecules/button/Button.component.tsx
> +  isDisable?: boolean;
Should be`isDisabled`

2023-02-27 11:24 UTC, pasinducw requested changes
Please address Dalana's comment

2023-02-28 07:40 UTC, supunTE commented on apps/client/src/components/molecules/button/Button.component.tsx
> +  isDisable?: boolean;
fixed

2023-03-01 10:06 UTC, pasinducw approved these changes

2023-03-04 03:59 UTC, dalanad approved these changes

2023-03-09 05:47 UTC, merged