[Solved #65] create add player effect
the-ai-team/razor pull request #75
Opened 2023-03-22 08:47 UTC by supunTE

Solved #65 
- Create an effect for `add-player`
- Add netlify redirects file

2023-03-22 09:34 UTC, supunTE commented
Working on unit tests

2023-03-28 12:36 UTC, dalanad requested changes

2023-03-28 12:36 UTC, dalanad commented on libs/store/src/lib/effects/player.ts
> +  dispatch.game.addPlayerReducer({
why does `addPlayerReducer` has reducer as a suffix and `setTournamentState` doesn't ?

2023-03-29 12:39 UTC, supunTE commented on libs/store/src/lib/effects/player.ts
> +  dispatch.game.addPlayerReducer({
`setTournamentState` is an effect, not a reducer. In our application effects will call necessary reducers to update the store. (Sometimes other effects also). Reducers to fundamental updates on store like add, remove, update while effects process data and pass to effect.

 Here AddPlayer effect will call addPlayer reducer with processed data.

2023-04-02 01:28 UTC, dalanad approved these changes

2023-04-11 12:34 UTC, merged

2023-04-11 12:34 UTC, supunTE commented
Solved #65