[Related #76] Race track background
the-ai-team/razor pull request #77
Opened 2023-03-29 11:59 UTC by supunTE

Related #76 
- Design customizable race track background.

`<= 2 Players`
![image](https://user-images.githubusercontent.com/33794760/228527756-e82fb339-0ce4-48ea-a278-459954ccac31.png)

`<= 4`
![image](https://user-images.githubusercontent.com/33794760/228527898-2601c076-f833-4a95-aafc-5f17c15fe6a4.png)

`<=6`
![image](https://user-images.githubusercontent.com/33794760/228528585-cb4b6149-0538-4288-886a-c4be444dd7df.png)

`>6`
![image](https://user-images.githubusercontent.com/33794760/228528692-42822bb8-0534-4729-82c9-17c8336b72fc.png)

2023-04-17 08:53 UTC, dalanad requested changes

2023-04-17 08:53 UTC, dalanad commented on apps/client/src/pages/race/templates/race-data.ts
> +export const getRaceTrackRowColumnSizes = (): number => {
Missing comments on above three functions. also add an empty line between functions

2023-04-17 08:53 UTC, dalanad commented on apps/client/src/pages/race/Race.page.tsx
> +      setRaceId(null);
Do we need to do this?

2023-05-05 06:28 UTC, supunTE commented on apps/client/src/pages/race/templates/race-data.ts
> +export const getRaceTrackRowColumnSizes = (): number => {
updated 3bff0754371ddd4c7c8fa3206af516590755243f

2023-05-05 06:28 UTC, supunTE commented on apps/client/src/pages/race/Race.page.tsx
> +      setRaceId(null);
Removed

2023-05-05 08:10 UTC, dalanad approved these changes

2023-05-08 03:25 UTC, merged