[Solved #82] implement socket schema validation
the-ai-team/razor pull request #83
Opened 2023-04-10 10:14 UTC by supunTE

- Refactor socket protocols into an object
- Fix uuid package (which was not installed in package.json earlier)
- Implement auth token validation
- Make compound schemas for protocols (Join lobby, Create Lobby, Race Start)
- Inferred types from compound schemas
- Implement socket schema validation, created a map for protocols-schemas

2023-05-08 15:56 UTC, dalanad requested changes

2023-05-08 15:56 UTC, dalanad commented on libs/models/src/lib/sockets/protocols.ts
> +export const socketProtocols = {
Capitalize First letter

2023-05-08 15:56 UTC, dalanad commented on apps/server/src/utils/authtoken.ts
> +export function generateAuthToken(): string {
Put in comments

2023-06-11 11:19 UTC, supunTE commented on libs/models/src/lib/sockets/protocols.ts
> +export const socketProtocols = {
Updated 17c1260820a76a66b5e53d8da25f78656637797f

2023-06-11 11:19 UTC, supunTE commented on apps/server/src/utils/authtoken.ts
> +export function generateAuthToken(): string {
comments added
ee3669d7963e4244913ef2f9d707be0895d67cb1

2023-06-11 12:56 UTC, dalanad approved these changes

2023-06-11 14:06 UTC, merged