[Solved #86] server race timer
the-ai-team/razor pull request #87
Opened 2023-04-17 04:35 UTC by supunTE

- Add race timeout from the server side.
- When race timeout it publish an event.

2023-05-08 18:47 UTC, dalanad requested changes

2023-05-08 18:47 UTC, dalanad commented on apps/server/src/controllers/start-race.controller.ts
> +    pubsub.publish(PubSubEvents.RaceTimout, {
don't we have to check if the race has already started or not? before missing timeout

2023-06-11 12:51 UTC, supunTE commented on apps/server/src/controllers/start-race.controller.ts
> +    pubsub.publish(PubSubEvents.RaceTimout, {
This is the start race controller, which triggers when someone start a race

2023-06-22 04:28 UTC, dalanad commented on apps/server/src/controllers/start-race.controller.ts
> +    pubsub.publish(PubSubEvents.RaceTimout, {
@supunTE let's discuss this later.

2023-06-22 04:28 UTC, dalanad approved these changes

2023-06-22 04:40 UTC, merged