[Related #93] Player list template
the-ai-team/razor pull request #96
Opened 2023-06-29 13:26 UTC by supunTE

- created playerlist template (component) and its story
- created room page (there're some updates from another PR)

2023-06-30 03:52 UTC, supunTE commented on apps/client/src/pages/room/Room.page.tsx
> +    <Provider store={store}>
This `room.page.tsx` contain some test codes which were removed and updates #95

2023-10-10 03:15 UTC, dalanad requested changes

2023-10-10 03:15 UTC, dalanad commented on apps/client/src/pages/room/templates/player-list/PlayerList.template.tsx
> +    containerRef.current?.addEventListener('scroll', containerScroll);
remove the event listener on cleanup

2023-10-10 03:15 UTC, dalanad commented on apps/client/src/pages/room/templates/player-list/PlayerList.template.tsx
> +    return <div></div>;
is `div` needed or can we use `null`

2023-10-16 11:06 UTC, supunTE commented on apps/client/src/pages/room/templates/player-list/PlayerList.template.tsx
> +    containerRef.current?.addEventListener('scroll', containerScroll);
Fixed

2023-10-16 11:06 UTC, supunTE commented on apps/client/src/pages/room/templates/player-list/PlayerList.template.tsx
> +    return <div></div>;
Fixed

2023-10-16 12:28 UTC, dalanad approved these changes

2023-10-16 13:05 UTC, merged